import type { SupportedLocale } from "@diaconia/shared";

const adminLabels = {
  es: {
    // Sign in
    signInSubtitle: "Ingresá con tu número de WhatsApp, Google o Apple. Solo usuarios invitados pueden acceder.",
    accessTokenLabel: "Token de acceso",
    accessTokenPlaceholder: "Token de desarrollo",
    signingIn: "Ingresando…",
    signIn: "Ingresar",
    invalidToken: "No se pudo validar la sesión. Intentá de nuevo.",
    authTitle: "Diaconia",
    authSubtitle: "Por favor ingresá para continuar",
    socialOr: "o",
    phoneNumber: "Número de teléfono",
    verificationCode: "Código de verificación",
    verificationCodePlaceholder: "Ingresá el código",
    sendingCode: "Enviando código…",
    continue: "Continuar",
    verifying: "Verificando…",
    verify: "Verificar",
    useDifferentNumber: "Usar otro número",
    appleSignIn: "Apple",
    googleSignIn: "Google",
    phoneCountry: "País del teléfono",
    authGenericError: "No se pudo completar el ingreso. Intentá de nuevo.",
    authAccountNotFound: "No encontramos una cuenta para ese número.",
    authInvalidCode: "El código no es válido. Verificá el código e intentá de nuevo.",
    authMissingPhone: "Ingresá un número de teléfono válido.",
    authAlreadySignedIn: "Ya hay una sesión iniciada. Salí de esa sesión e intentá de nuevo.",
    authInviteRequired: "Tu cuenta existe, pero todavía no está habilitada para acceder a Diaconia.",
    authTryAgain: "Intentar de nuevo",
    authInvalidSession: "Tu sesión expiró o no es válida. Salí e ingresá de nuevo.",
    authMissingSession: "Iniciá sesión para continuar.",

    // Nav
    dashboard: "Inicio",
    meetings: "Reuniones",
    members: "Miembros",
    settings: "Configuración",
    toggleSidebar: "Abrir/cerrar menú",

    // App bar / user menu
    userMenu: "Menú de usuario",
    profile: "Perfil",
    signOut: "Salir",

    // Profile editor
    editProfile: "Editar perfil",
    displayName: "Nombre completo",
    email: "Correo electrónico",
    phone: "Teléfono",
    avatarUrl: "URL de foto de perfil",
    cancel: "Cancelar",
    saveProfile: "Guardar perfil",

    // Dashboard
    greeting: (name: string) => `Hola, ${name}`,
    greetingFallback: "Bienvenido",
    plannedMeetings: "Reuniones planificadas",
    plannedMeetingsDesc: "Reuniones pendientes de informe",
    openPrayerRequests: "Pedidos de oración abiertos",
    openPrayerRequestsDesc: "Pedidos sin respuesta",
    meetingReports: "Informes de reunión",
    meetingReportsDesc: "Informes enviados por facilitadores",
    quickLinks: "Accesos rápidos",
    viewAllMeetings: "Ver todas las reuniones",
    viewMembers: "Ver miembros",

    // Meetings list
    meetingsSubtitle: "Todas las reuniones de grupos de confianza e informes de campo",
    exportCsv: "Exportar CSV",
    from: "Desde",
    to: "Hasta",
    groupId: "ID de grupo",
    filter: "Filtrar",
    loadingMeetings: "Cargando reuniones…",
    loading: "Cargando…",
    colDate: "Fecha",
    colGroup: "Grupo",
    colFacilitator: "Facilitador",
    colFollowUp: "Seguimiento",
    colPhotos: "Fotos",
    colPrayer: "Oración",
    colNotes: "Notas",
    noRequests: "Sin pedidos",
    noNotes: "Sin notas",
    noMeetings: "No hay reuniones para mostrar.",
    meetingPhoto: "Foto de reunión",

    // Members
    membersSubtitle: "Facilitadores y miembros de los grupos",
    facilitators: "Facilitadores",
    found: (n: number) => `${n} encontrado${n !== 1 ? "s" : ""}`,
    colName: "Nombre",
    colCommunity: "Comunidad",
    colMeetings: "Reuniones",
    noFacilitators: "No se encontraron facilitadores.",
    groupMembers: "Miembros del grupo",
    membersComing: "Gestión de miembros próximamente",
    membersComingDesc:
      "Las listas de miembros por grupo estarán disponibles aquí cuando la API esté lista.",

    // Settings
    settingsSubtitle: "Preferencias y configuración de la aplicación",
    preferences: "Preferencias",
    language: "Idioma",
    languageDesc: "Elegí el idioma para fechas y etiquetas",
    apiEndpoint: "Servidor API",
    advanced: "Avanzado",
    moreSettingsSoon: "Más configuraciones próximamente",
    moreSettingsDesc:
      "La gestión de grupos, notificaciones y roles de usuario aparecerá aquí.",

    // Status
    meetingsCount: (n: number) => `${n} reunión${n !== 1 ? "es" : ""}`,
    groups: "Grupos",
    colStatus: "Estado",
    save: "Guardar",

    // Groups CRUD
    newGroup: "Nuevo grupo",
    editGroup: "Editar grupo",
    deleteGroup: "Eliminar grupo",
    groupDetail: "Detalle del grupo",
    backToGroups: "Volver a grupos",
    groupName: "Nombre del grupo",
    groupCommunity: "Comunidad",
    groupFacilitator: "Facilitador",
    groupActive: "Activo",
    groupInactive: "Inactivo",
    loanSteward: "Custodio de préstamos",
    groupSaved: "Grupo guardado",
    groupDeleted: "Grupo desactivado",
    groupsFound: (n: number) => `${n} grupo${n !== 1 ? "s" : ""}`,
    noGroups: "No se encontraron grupos.",
    noGroupMembers: "Sin miembros registrados.",
    createGroupFirst: "Primero creá un grupo",
    noGroupsForMeeting: "No hay grupos disponibles. Creá un grupo antes de agregar una reunión.",

    // Group leadership
    steeringCommittee: "Comité directivo",
    groupPresident: "Presidente/a",
    groupSecretary: "Secretario/a",
    groupTreasurer: "Tesorero/a",
    positionPresident: "Presidente/a",
    positionSecretary: "Secretario/a",
    positionTreasurer: "Tesorero/a",
    noPosition: "Sin cargo",
    assignPosition: "Asignar cargo",

    // Chaplain
    chaplain: "Capellán",
    chaplainAssigned: "Capellán asignado",
    chaplainAttended: "Capellán presente",
    noChaplain: "Sin capellán asignado",
    chaplainOptional: "Capellán (opcional)",
    selectChaplain: "Seleccionar capellán…",
    noChaplainAttended: "Sin capellán presente",

    // Location
    meetingLocation: "Ubicación",
    locationPin: "Pin de ubicación",
    latitude: "Latitud",
    longitude: "Longitud",
    noLocation: "Sin ubicación registrada",
    viewOnMap: "Ver en mapa",
    mapView: "Mapa",
    listView: "Lista",

    // Profile
    myProfile: "Mi perfil",
    editMyProfile: "Editar mi perfil",
    profileSaved: "Perfil guardado",

    // Members CRUD
    newMember: "Nuevo miembro",
    editMember: "Editar miembro",
    deleteMember: "Eliminar miembro",
    memberDetail: "Detalle del miembro",
    backToMembers: "Volver a miembros",
    colEmail: "Correo",
    colPhone: "Teléfono",
    colRole: "Rol",
    colCreated: "Creado",
    roleFacilitator: "Facilitador",
    roleAdmin: "Administrador",
    authSubjectLabel: "ID del proveedor de identidad",
    noGroup: "Sin grupo",
    noEmail: "Sin correo",
    noPhone: "Sin teléfono",
    memberSaved: "Miembro guardado",
    memberDeleted: "Miembro eliminado",
    confirmDeleteTitle: "¿Eliminar permanentemente?",
    confirmDeleteDesc: "Esta acción no se puede deshacer.",
    deleteBtn: "Sí, eliminar",
    saving: "Guardando…",
    deleting: "Eliminando…",
    membersFound: (n: number) => `${n} miembro${n !== 1 ? "s" : ""}`,

    // Meetings CRUD
    newMeeting: "Nueva reunión",
    editMeeting: "Editar reunión",
    deleteMeeting: "Eliminar reunión",
    meetingDetail: "Detalle de la reunión",
    viewMeetingDetail: "Ver detalle completo",
    backToMeetings: "Volver a reuniones",
    meetingSaved: "Reunión guardada",
    meetingDeleted: "Reunión eliminada",
    attendance: "Asistencia",
    prayerRequests: "Pedidos de oración",
    present: "Presente",
    absent: "Ausente",
    excused: "Justificado",
    noAttendance: "Sin registros de asistencia",
    noPrayerRequests: "Sin pedidos de oración",
    selectGroup: "Seleccionar grupo…",
    dateTime: "Fecha y hora",
    submittedAt: "Enviado",
    followUpLabel: "Seguimiento",
    followUpNone: "Ninguno",
    followUpFinancial: "Financiero",
    followUpTraining: "Capacitación",
    followUpWellbeing: "Bienestar",
    followUpDocumentation: "Documentación",
    followUpOther: "Otro",
    photos: "Fotos",
    noPhotos: "Sin fotos",
    overview: "Resumen",
    meetingsFound: (n: number) => `${n} reunión${n !== 1 ? "es" : ""}`,
  },

  en: {
    // Sign in
    signInSubtitle: "Sign in with your WhatsApp phone number, Google, or Apple. Invited users only.",
    accessTokenLabel: "Access token",
    accessTokenPlaceholder: "Development token",
    signingIn: "Signing in…",
    signIn: "Sign in",
    invalidToken: "Could not validate the session. Try again.",
    authTitle: "Diaconia",
    authSubtitle: "Please sign in to continue",
    socialOr: "or",
    phoneNumber: "Phone number",
    verificationCode: "Verification code",
    verificationCodePlaceholder: "Enter the code",
    sendingCode: "Sending code…",
    continue: "Continue",
    verifying: "Verifying…",
    verify: "Verify",
    useDifferentNumber: "Use a different number",
    appleSignIn: "Apple",
    googleSignIn: "Google",
    phoneCountry: "Phone country",
    authGenericError: "Could not complete sign in. Try again.",
    authAccountNotFound: "Could not find an account for that number.",
    authInvalidCode: "The code is not valid. Check the code and try again.",
    authMissingPhone: "Enter a valid phone number.",
    authAlreadySignedIn: "You are already signed in. Sign out of that session and try again.",
    authInviteRequired: "Your account exists, but it is not enabled for Diaconia access yet.",
    authTryAgain: "Try again",
    authInvalidSession: "Your session expired or is not valid. Sign out and sign in again.",
    authMissingSession: "Sign in to continue.",

    // Nav
    dashboard: "Dashboard",
    meetings: "Meetings",
    members: "Members",
    settings: "Settings",
    toggleSidebar: "Toggle sidebar",

    // App bar / user menu
    userMenu: "User menu",
    profile: "Profile",
    signOut: "Sign out",

    // Profile editor
    editProfile: "Edit Profile",
    displayName: "Display Name",
    email: "Email",
    phone: "Phone",
    avatarUrl: "Avatar URL",
    cancel: "Cancel",
    saveProfile: "Save Profile",

    // Dashboard
    greeting: (name: string) => `Welcome back, ${name}`,
    greetingFallback: "Welcome back",
    plannedMeetings: "Planned Meetings",
    plannedMeetingsDesc: "Meetings awaiting submission",
    openPrayerRequests: "Open Prayer Requests",
    openPrayerRequestsDesc: "Prayer requests still open",
    meetingReports: "Meeting Reports",
    meetingReportsDesc: "Reports submitted by facilitators",
    quickLinks: "Quick Links",
    viewAllMeetings: "View all meetings",
    viewMembers: "View members",

    // Meetings list
    meetingsSubtitle: "All trust group meetings and field reports",
    exportCsv: "Export CSV",
    from: "From",
    to: "To",
    groupId: "Group ID",
    filter: "Filter",
    loadingMeetings: "Loading meetings…",
    loading: "Loading…",
    colDate: "Date",
    colGroup: "Group",
    colFacilitator: "Facilitator",
    colFollowUp: "Follow-up",
    colPhotos: "Photos",
    colPrayer: "Prayer",
    colNotes: "Notes",
    noRequests: "No requests",
    noNotes: "No notes",
    noMeetings: "No meetings to show.",
    meetingPhoto: "Meeting photo",

    // Members
    membersSubtitle: "Facilitators and group members",
    facilitators: "Facilitators",
    found: (n: number) => `${n} found`,
    colName: "Name",
    colCommunity: "Community",
    colMeetings: "Meetings",
    noFacilitators: "No facilitators found.",
    groupMembers: "Group Members",
    membersComing: "Member management coming soon",
    membersComingDesc:
      "Group-level member lists will be available here once the roster API is ready.",

    // Settings
    settingsSubtitle: "Application preferences and configuration",
    preferences: "Preferences",
    language: "Language",
    languageDesc: "Choose the display language for dates and labels",
    apiEndpoint: "API Endpoint",
    advanced: "Advanced",
    moreSettingsSoon: "More settings coming soon",
    moreSettingsDesc: "Group management, notifications, and user roles will appear here.",

    // Status
    meetingsCount: (n: number) => `${n} meeting${n !== 1 ? "s" : ""}`,
    groups: "Groups",
    colStatus: "Status",
    save: "Save",

    // Groups CRUD
    newGroup: "New Group",
    editGroup: "Edit Group",
    deleteGroup: "Delete Group",
    groupDetail: "Group Details",
    backToGroups: "Back to Groups",
    groupName: "Group Name",
    groupCommunity: "Community",
    groupFacilitator: "Loan Steward",
    loanSteward: "Loan Steward",
    groupActive: "Active",
    groupInactive: "Inactive",
    groupSaved: "Group saved",
    groupDeleted: "Group deactivated",
    groupsFound: (n: number) => `${n} group${n !== 1 ? "s" : ""}`,
    noGroups: "No groups found.",
    noGroupMembers: "No members registered.",
    createGroupFirst: "Create a group first",
    noGroupsForMeeting: "No groups available. Create a group before adding a meeting.",

    // Group leadership
    steeringCommittee: "Steering Committee",
    groupPresident: "President",
    groupSecretary: "Secretary",
    groupTreasurer: "Treasurer",
    positionPresident: "President",
    positionSecretary: "Secretary",
    positionTreasurer: "Treasurer",
    noPosition: "No position",
    assignPosition: "Assign position",

    // Chaplain
    chaplain: "Chaplain",
    chaplainAssigned: "Assigned Chaplain",
    chaplainAttended: "Chaplain Attended",
    noChaplain: "No chaplain assigned",
    chaplainOptional: "Chaplain (optional)",
    selectChaplain: "Select chaplain…",
    noChaplainAttended: "No chaplain attended",

    // Location
    meetingLocation: "Location",
    locationPin: "Location Pin",
    latitude: "Latitude",
    longitude: "Longitude",
    noLocation: "No location recorded",
    viewOnMap: "View on map",
    mapView: "Map",
    listView: "List",

    // Profile
    myProfile: "My Profile",
    editMyProfile: "Edit My Profile",
    profileSaved: "Profile saved",

    // Members CRUD
    newMember: "New Member",
    editMember: "Edit Member",
    deleteMember: "Delete Member",
    memberDetail: "Member Details",
    backToMembers: "Back to Members",
    colEmail: "Email",
    colPhone: "Phone",
    colRole: "Role",
    colCreated: "Created",
    roleFacilitator: "Facilitator",
    roleAdmin: "Admin",
    authSubjectLabel: "Identity provider ID",
    noGroup: "No group",
    noEmail: "No email",
    noPhone: "No phone",
    memberSaved: "Member saved",
    memberDeleted: "Member deleted",
    confirmDeleteTitle: "Delete permanently?",
    confirmDeleteDesc: "This action cannot be undone.",
    deleteBtn: "Yes, delete",
    saving: "Saving…",
    deleting: "Deleting…",
    membersFound: (n: number) => `${n} member${n !== 1 ? "s" : ""}`,

    // Meetings CRUD
    newMeeting: "New Meeting",
    editMeeting: "Edit Meeting",
    deleteMeeting: "Delete Meeting",
    meetingDetail: "Meeting Details",
    viewMeetingDetail: "View full details",
    backToMeetings: "Back to Meetings",
    meetingSaved: "Meeting saved",
    meetingDeleted: "Meeting deleted",
    attendance: "Attendance",
    prayerRequests: "Prayer Requests",
    present: "Present",
    absent: "Absent",
    excused: "Excused",
    noAttendance: "No attendance records",
    noPrayerRequests: "No prayer requests",
    selectGroup: "Select group…",
    dateTime: "Date & Time",
    submittedAt: "Submitted",
    followUpLabel: "Follow-up",
    followUpNone: "None",
    followUpFinancial: "Financial",
    followUpTraining: "Training",
    followUpWellbeing: "Wellbeing",
    followUpDocumentation: "Documentation",
    followUpOther: "Other",
    photos: "Photos",
    noPhotos: "No photos",
    overview: "Overview",
    meetingsFound: (n: number) => `${n} meeting${n !== 1 ? "s" : ""}`,
  },
} as const satisfies Record<SupportedLocale, object>;

export type AdminLabels = (typeof adminLabels)["es"];
export function t(locale: SupportedLocale): AdminLabels {
  return adminLabels[locale] as AdminLabels;
}

export function localizeRouteError(
  payload: { error?: string; code?: string } | null,
  labels: AdminLabels,
  status?: number,
) {
  if (payload?.code === "UNAUTHENTICATED" || /invalid bearer token/i.test(payload?.error ?? "")) {
    return labels.authInvalidSession;
  }

  if (/missing bearer token/i.test(payload?.error ?? "")) {
    return labels.authMissingSession;
  }

  if (payload?.code === "INVITE_REQUIRED" || /invited active user required/i.test(payload?.error ?? "")) {
    return labels.authInviteRequired;
  }

  return payload?.error ?? (status ? `Error ${status}` : labels.authGenericError);
}
